file_format: "1"
id: ergovison
name: ErgoVision
type: shield
url: https://github.com/VBlibrary/zmk-config
requires: [nice_nano_v2]
features:
  - keys
  - pointer
siblings:
  - ergovision_left
  - ergovision_right